[program:janku-image-studio]
environment=PROC_NAME="%(program_name)s"
directory=/workspace/janku-image-studio
command=/opt/supervisor-scripts/janku-image-studio.sh
autostart=true
autorestart=true
startsecs=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
